server:
  port: 8080
  servlet:
    context-path: /blog
spring:
  application:
    name: blog

  #mysql
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/blog
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    database: 2
  #security
  security:
    user:
      name: root
      password: root
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

